#!/bin/bash

alias lla='ls -alF'
alias vi="nvim"

# if [[ -e '/opt/nvim/bin/nvim' ]]; then
#     alias vi='/opt/nvim/bin/nvim'
# elif [[ -e '/opt/homebrew/bin/nvim' ]]; then
#     alias vi='/opt/homebrew/bin/nvim'
# elif [[ -e '/usr/bin/nvim' ]]; then
#     alias vi='/usr/bin/nvim'
# fi

# [[ $commands[kubectl] ]] && source <(kubectl completion zsh)
alias k='kubectl'

alias ga='git add'
alias gs='git status'
alias gc='git commit'
alias gp='git pull'
