#!/bin/bash

alias lla='ls -alF'

if [[ -e '/opt/nvim/bin/nvim' ]]; then
    alias vi='/opt/nvim/bin/nvim'
elif [[ -e '/opt/homebrew/bin/nvim' ]]; then
    alias vi='/opt/homebrew/bin/nvim'
fi

[[ $commands[kubectl] ]] && source <(kubectl completion zsh)
alias k='kubectl'

alias gs='git status'
